%define	MAXPC_LS_BY_EPORT_IP	10
%define	MAXL_LS_BY_EPORT_IP	0x1000
%define	MAXC_LS_BY_EPORT_IP	100

%define	MAXPC_LS_BY_PORT_IP	10
%define	MAXL_LS_BY_PORT_IP	0x1000
%define	MAXC_LS_BY_PORT_IP	100

%define	MAXPC_LS_BY_EPROTO_IP	9
%define	MAXL_LS_BY_EPROTO_IP	0x1000
%define	MAXC_LS_BY_EPROTO_IP	100

%define	MAXPC_LS_BY_PROTO_IP	9
%define	MAXL_LS_BY_PROTO_IP	0x1000
%define	MAXC_LS_BY_PROTO_IP	100

%define	MAXPC_LS_BY_IP		8
%define	MAXL_LS_BY_IP		0x1000
%define	MAXC_LS_BY_IP		100

%define	MAXPC_ALO_DEV_IN_NAME	2
%define	MAXL_ALO_DEV_IN_NAME	0x1000
%define	MAXC_ALO_DEV_IN_NAME	100

%define	MAXPC_DENY_DEV_IN_NAME	2
%define	MAXL_DENY_DEV_IN_NAME	0x1000
%define	MAXC_DENY_DEV_IN_NAME	100

%define	MAXPC_LS_BY_EACH_IP_LOCAL	8
%define	MAXL_LS_BY_EACH_IP_LOCAL	0x1000
%define	MAXC_LS_BY_EACH_IP_LOCAL	100

%define	MAXPC_LS_FULL_BY_EACH_IP  8
%define	MAXL_LS_FULL_BY_EACH_IP	  0x1000
%define	MAXC_LS_FULL_BY_EACH_IP	  100

%define	MAXPC_FULL_LOG_BY_EACH_IP 4
%define	MAXL_FULL_LOG_BY_EACH_IP  0x1000
%define	MAXC_FULL_LOG_BY_EACH_IP  100

%define	MAXPC_LS_BY_EPROTO_EIP	9
%define	MAXL_LS_BY_EPROTO_EIP	0x1000
%define	MAXC_LS_BY_EPROTO_EIP	100

%define	MAXPC_LS_BY_PROTO_EIP	9
%define	MAXL_LS_BY_PROTO_EIP	0x1000
%define	MAXC_LS_BY_PROTO_EIP	100

%define	MAXPC_LS_BY_EPORT_EIP	10
%define	MAXL_LS_BY_EPORT_EIP	0x1000
%define	MAXC_LS_BY_EPORT_EIP	100

%define	MAXPC_LS_BY_PORT_EIP	10
%define	MAXL_LS_BY_PORT_EIP	0x1000
%define	MAXC_LS_BY_PORT_EIP	100

%define	MAXPC_IFACE_TL	4
%define	MAXL_IFACE_TL	0x1000
%define	MAXC_IFACE_TL	100

%define	MAXPC_EPROTO_EIP_TL	5
%define	MAXL_EPROTO_EIP_TL	0x1000
%define	MAXC_EPROTO_EIP_TL	100

%define	MAXPC_PROTO_IP_EACH_TL	5
%define	MAXL_PROTO_IP_EACH_TL	0x1000
%define	MAXC_PROTO_IP_EACH_TL	100

%define	MAXPC_PROTO_IP_TL	5
%define	MAXL_PROTO_IP_TL	0x1000
%define	MAXC_PROTO_IP_TL	100

%define	MAXPC_LM_BY_EPORT_EIP	6
%define	MAXL_LM_BY_EPORT_EIP	0x1000
%define	MAXC_LM_BY_EPORT_EIP	100

%define	MAXPC_LM_BY_PORT_IP_EACH 6
%define	MAXL_LM_BY_PORT_IP_EACH	 0x1000
%define	MAXC_LM_BY_PORT_IP_EACH	 100

%define	MAXPC_LM_BY_PORT_IP	6
%define	MAXL_LM_BY_PORT_IP	0x1000
%define	MAXC_LM_BY_PORT_IP	100

%define	MAXPC_PROTO_EACH_TL	4
%define	MAXL_PROTO_EACH_TL	0x1000
%define	MAXC_PROTO_EACH_TL	100

%define	MAXPC_PROTO_RANGE_TL	4
%define	MAXL_PROTO_RANGE_TL	0x1000
%define	MAXC_PROTO_RANGE_TL	100

%define	MAXPC_EACH_PR_RANGE_TL	5
%define	MAXL_EACH_PR_RANGE_TL	0x1000
%define	MAXC_EACH_PR_RANGE_TL	100

%define	MAXPC_PR_RANGE_TL	5
%define	MAXL_PR_RANGE_TL	0x1000
%define	MAXC_PR_RANGE_TL	100

%define	MAXPC_IPE_RANGE_TL	4
%define	MAXL_IPE_RANGE_TL	0x1000
%define	MAXC_IPE_RANGE_TL	100

%define	MAXPC_IP_RANGE_TL	4
%define	MAXL_IP_RANGE_TL	0x1000
%define	MAXC_IP_RANGE_TL	100

%define	MAXPC_ALO_IP_PTYPE_IN	3
%define	MAXL_ALO_IP_PTYPE_IN	0x1000
%define	MAXC_ALO_IP_PTYPE_IN	100

%define	MAXPC_ALO_DEV	1
%define	MAXL_ALO_DEV	0x1000
%define	MAXC_ALO_DEV	100

%define	MAXPC_ALO_IP_IN_DEV	2
%define	MAXL_ALO_IP_IN_DEV	0x1000
%define	MAXC_ALO_IP_IN_DEV	100

%define	MAXPC_ALO_IP_IN_NAME	2
%define	MAXL_ALO_IP_IN_NAME	0x1000
%define	MAXC_ALO_IP_IN_NAME	100

%define	MAXPC_ALO_IP_IN_TYPE	2
%define	MAXL_ALO_IP_IN_TYPE	0x1000
%define	MAXC_ALO_IP_IN_TYPE	100

%define	MAXPC_ALO_IP_GLOBAL	1
%define	MAXL_ALO_IP_GLOBAL	0x1000
%define	MAXC_ALO_IP_GLOBAL	100

%define MAXL_LOG_FILE	0x1000
%define MAXC_LOG_FILE	100
%define	MAXPC_LOG_FILE	3

%define MAXL_STAT_GLOBAL	0x1000
%define	MAXC_STAT_GLOBAL	100
%define MAXPC_STAT_GLOBAL	3

%define	MAXPC_STAT_BY_DEV	4
%define	MAXL_STAT_BY_DEV	0x1000
%define	MAXC_STAT_BY_DEV	100

%define	MAXPC_STAT_BY_IP_GLOBAL	4
%define	MAXL_STAT_BY_IP_GLOBAL	0x1000
%define	MAXC_STAT_BY_IP_GLOBAL	100

%define	MAXPC_STAT_BY_IP_DEV	5
%define	MAXL_STAT_BY_IP_DEV	0x1000
%define	MAXC_STAT_BY_IP_DEV	100

%define	MAXPC_DENY_IP_GLOBAL	1
%define	MAXL_DENY_IP_GLOBAL	0x1000
%define	MAXC_DENY_IP_GLOBAL	100

%define	MAXPC_DENY_IP_IN_TYPE	2
%define	MAXL_DENY_IP_IN_TYPE	0x1000
%define	MAXC_DENY_IP_IN_TYPE	100

%define	MAXPC_DENY_IP_IN_NAME	2
%define	MAXL_DENY_IP_IN_NAME	0x1000
%define	MAXC_DENY_IP_IN_NAME	100

%define	MAXPC_DENY_IP_IN_DEV	2
%define	MAXL_DENY_IP_IN_DEV	0x1000
%define	MAXC_DENY_IP_IN_DEV	100

%define	MAXPC_DENY_DEV		1
%define	MAXL_DENY_DEV		0x1000
%define	MAXC_DENY_DEV		100

%define	MAXPC_TIME_STAMP	1
%define	MAXL_TIME_STAMP		0x1000
%define	MAXC_TIME_STAMP		1

%define	MAXPC_LOG_BY_IP		4
%define	MAXL_LOG_BY_IP		0x1000
%define	MAXC_LOG_BY_IP		100

%define	MAXPC_STAT_TIME_ON	4
%define	MAXL_STAT_TIME_ON	0x1000
%define	MAXC_STAT_TIME_ON	100

%define	MAXPC_LOG_BY_EACH_IP	4
%define	MAXL_LOG_BY_EACH_IP	0x1000
%define	MAXC_LOG_BY_EACH_IP	100

%define	MAXPC_SAVE_ON_TIME	1
%define	MAXL_SAVE_ON_TIME	0x1000
%define	MAXC_SAVE_ON_TIME	1

%define	MAXPC_RS_BY_PROTO_GLOBAL 1
%define MAXL_RS_BY_PROTO_GLOBAL	0x1000
%define MAXC_RS_BY_PROTO_GLOBAL	100

%define MAXPC_AL_ONLY_PROTO_GLOBAL 1
%define MAXL_AL_ONLY_PROTO_GLOBAL 0x1000
%define MAXC_AL_ONLY_PROTO_GLOBAL 100

%define	MAXPC_RS_BY_PROTO_IDEV	2
%define	MAXL_RS_BY_PROTO_IDEV	0x1000
%define	MAXC_RS_BY_PROTO_IDEV	100

%define	MAXPC_RS_BY_PROTO_NAME	2
%define	MAXL_RS_BY_PROTO_NAME	0x1000
%define	MAXC_RS_BY_PROTO_NAME	100

%define	MAXPC_AL_BY_PROTO_IDEV	2
%define	MAXL_AL_BY_PROTO_IDEV	0x1000
%define	MAXC_AL_BY_PROTO_IDEV	100

%define	MAXPC_AL_BY_PROTO_NAME	2
%define	MAXL_AL_BY_PROTO_NAME	0x1000
%define	MAXC_AL_BY_PROTO_NAME	100

%define	MAXPC_RS_BY_PORT_GLOBAL 2
%define	MAXL_RS_BY_PORT_GLOBAL	0x1000
%define	MAXC_RS_BY_PORT_GLOBAL	100

%define	MAXPC_AL_BY_PORT_GLOBAL 2
%define	MAXL_AL_BY_PORT_GLOBAL	0x1000
%define	MAXC_AL_BY_PORT_GLOBAL	100

%define	MAXPC_AL_BY_PORT_ITYPE	3
%define	MAXL_AL_BY_PORT_ITYPE	0x1000
%define	MAXC_AL_BY_PORT_ITYPE	100

%define	MAXPC_RS_BY_PORT_ITYPE	3
%define	MAXL_RS_BY_PORT_ITYPE	0x1000
%define	MAXC_RS_BY_PORT_ITYPE	100

%define	MAXPC_RS_BY_PROTO_ITYPE	2
%define	MAXL_RS_BY_PROTO_ITYPE	0x1000
%define	MAXC_RS_BY_PROTO_ITYPE	100

%define	MAXPC_RS_BY_PORT_IDEV	3
%define	MAXL_RS_BY_PORT_IDEV	0x1000
%define	MAXC_RS_BY_PORT_IDEV	100

%define	MAXPC_AL_BY_PORT_IDEV	3
%define	MAXL_AL_BY_PORT_IDEV	0x1000
%define	MAXC_AL_BY_PORT_IDEV	100

%define	MAXPC_AL_BY_PROTO_ITYPE	2
%define	MAXL_AL_BY_PROTO_ITYPE	0x1000
%define	MAXC_AL_BY_PROTO_ITYPE	100

%define	MAXPC_RS_BY_PORT_NAME	3
%define	MAXL_RS_BY_PORT_NAME	0x1000
%define	MAXC_RS_BY_PORT_NAME	100

%define	MAXPC_AL_BY_PORT_NAME	3
%define	MAXL_AL_BY_PORT_NAME	0x1000
%define	MAXC_AL_BY_PORT_NAME	100

%define	MAXPC_BIN_STAT_GLOBAL	3
%define	MAXL_BIN_STAT_GLOBAL	0x1000
%define	MAXC_BIN_STAT_GLOBAL	100

%define	MAXPC_BIN_STAT_BY_DEV	4
%define	MAXL_BIN_STAT_BY_DEV	0x1000
%define	MAXC_BIN_STAT_BY_DEV	100

%define	MAXPC_BIN_STAT_BY_IP_GLOBAL	4
%define	MAXL_BIN_STAT_BY_IP_GLOBAL	0x1000
%define	MAXC_BIN_STAT_BY_IP_GLOBAL	100

%define	MAXPC_BIN_STAT_BY_IP_DEV 5
%define	MAXL_BIN_STAT_BY_IP_DEV	0x1000
%define	MAXC_BIN_STAT_BY_IP_DEV	100

%define	MAXPC_FULL_STAT_GLOBAL	3
%define	MAXL_FULL_STAT_GLOBAL	0x1000
%define	MAXC_FULL_STAT_GLOBAL	100

%define	MAXPC_FULL_STAT_BY_DEV	4
%define	MAXL_FULL_STAT_BY_DEV	0x1000
%define	MAXC_FULL_STAT_BY_DEV	100

%define	MAXPC_FULL_STAT_BY_IP_GLOBAL	4
%define	MAXL_FULL_STAT_BY_IP_GLOBAL	0x1000
%define	MAXC_FULL_STAT_BY_IP_GLOBAL	100

%define	MAXPC_FULL_STAT_BY_IP_DEV	5
%define	MAXL_FULL_STAT_BY_IP_DEV	0x1000
%define	MAXC_FULL_STAT_BY_IP_DEV	100

%define	MAXPC_BIN_FULL_STAT_GLOBAL	3
%define	MAXL_BIN_FULL_STAT_GLOBAL	0x1000
%define	MAXC_BIN_FULL_STAT_GLOBAL	100

%define	MAXPC_BIN_FULL_STAT_BY_DEV	4
%define	MAXL_BIN_FULL_STAT_BY_DEV	0x100
%define	MAXC_BIN_FULL_STAT_BY_DEV	100

%define	MAXPC_BIN_FULL_STAT_BY_IP_GLOBAL 4
%define	MAXL_BIN_FULL_STAT_BY_IP_GLOBAL	0x1000
%define	MAXC_BIN_FULL_STAT_BY_IP_GLOBAL 100

%define	MAXPC_BIN_FULL_STAT_BY_IP_DEV	5
%define	MAXL_BIN_FULL_STAT_BY_IP_DEV	0x1000
%define	MAXC_BIN_FULL_STAT_BY_IP_DEV	100

%define	MAXPC_LOG_BY_EACH_PORT	5
%define	MAXL_LOG_BY_EACH_PORT	0x1000
%define	MAXC_LOG_BY_EACH_PORT	100

%define	MAXPC_LOG_BY_PORT_IP	6
%define	MAXL_LOG_BY_PORT_IP	0x1000
%define	MAXC_LOG_BY_PORT_IP	100

%define	MAXPC_LOG_BY_PORT	5
%define	MAXL_LOG_BY_PORT	0x1000
%define	MAXC_LOG_BY_PORT	100

%define	MAXPC_LOG_BY_PROTO	4
%define	MAXL_LOG_BY_PROTO	0x1000
%define	MAXC_LOG_BY_PROTO	100

%define	MAXPC_LOG_BY_EACH_PROTO	4
%define	MAXL_LOG_BY_EACH_PROTO	0x1000
%define	MAXC_LOG_BY_EACH_PROTO	100

%define	MAXPC_LOG_BY_PORT_IP_EACH 6
%define	MAXL_LOG_BY_PORT_IP_EACH 0x1000
%define	MAXC_LOG_BY_PORT_IP_EACH 100

%define	MAXPC_LOG_BY_EPORT_EIP	6
%define	MAXL_LOG_BY_EPORT_EIP	0x1000
%define	MAXC_LOG_BY_EPORT_EIP	100

%define	MAXPC_LOG_BY_EACH_IP_LOCAL	4
%define	MAXL_LOG_BY_EACH_IP_LOCAL	0x1000
%define	MAXC_LOG_BY_EACH_IP_LOCAL	100

%define	MAXPC_LOG_BY_IP_LOCAL	4
%define	MAXL_LOG_BY_IP_LOCAL	0x1000
%define	MAXC_LOG_BY_IP_LOCAL	100

%define	MAXPC_DENY_IP_PTYPE_IN	3
%define	MAXL_DENY_IP_PTYPE_IN	0x1000
%define	MAXC_DENY_IP_PTYPE_IN	100

%define	MAXPC_LOG_BY_PROTO_IP	5
%define	MAXL_LOG_BY_PROTO_IP	0x1000
%define	MAXC_LOG_BY_PROTO_IP	100

%define	MAXPC_LOG_BY_PROTO_IP_EACH	5
%define	MAXL_LOG_BY_PROTO_IP_EACH	0x1000
%define	MAXC_LOG_BY_PROTO_IP_EACH	100

%define	MAXPC_LOG_BY_EPROTO_EIP	5
%define	MAXL_LOG_BY_EPROTO_EIP	0x1000
%define	MAXC_LOG_BY_EPROTO_EIP	100

%define	MAXPC_LS_BY_IFACE	7
%define	MAXL_LS_BY_IFACE	0x1000
%define	MAXC_LS_BY_IFACE	100

%define	MAXPC_LS_BY_EACH_IP	8
%define	MAXL_LS_BY_EACH_IP	0x1000
%define	MAXC_LS_BY_EACH_IP	100

%define	MAXPC_IP_ENTRY_LIST	2
%define	MAXL_IP_ENTRY_LIST	0x1000
%define	MAXC_IP_ENTRY_LIST	100

%define	MAXPC_PRIORITY	1
%define	MAXL_PRIORITY	0x1000
%define	MAXC_PRIORITY	1
